project:
  type: website
  output-dir: docs

website:
  title: "Nuclear Education Science of Technology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: overview.qmd
        text: Overview

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



