---
title: "Overview"
editor: visual
---

## Goals

The LIB NEST is established to help advance the existing scientific knowledge needed to enhance the

performance and safety of current nuclear systems through the followings:

• To uphold the implementation of the AFRA NEST agenda as relate to its human resource development and nuclear knowledge management.

• To contribute to the building of a solid scientific and technical basis for the development of future-generation nuclear systems • To enhances the objectives of the AFRA NEST and the IAEA in carrying on the LIB NEST function as a regional organization. • To support the preservation of essential knowledge in the field of nuclear science

## Aims and Objectives

The objective of LIB NEST is to facilitate awareness on the peaceful use of nuclear technology and networking in education, training in nuclear science and technology in Liberia through: Sharing information and resources on nuclear education and training;

• Developing harmonized approaches for education in Liberia, providing the basic knowledge and skills for students who are interested in furthering their postgraduate degrees in medical physics and nuclear physics and technology

• Promote Liberians to industrial and clinical trainings and practices for the protection of Environments, solving radiation crisis, solving contamination problems, energy crisis, etc

• The university of Liberia being the host , will facilitate the exchange of students , teachers and researchers

• Ensure the usage of web-based education and training and recognition of Liberia as one of the regional designated centers for professional nuclear science and technology

• Train and expose Liberians to both local and international workshops, training, Scholarships, conferences and regulations in the area of nuclear science technology in the world

• Enabling communication between the AFRA NEST, IAEA and other member organizations and other regional networks.

• Create exchange programs between the University of Liberia and other Universities in the world who offer Nuclear Physics and Technology
